### ISSUE TITLE
Compilation and run

### ISSUE THREAD

**Issue by michaelscheinfeild** [Lotemn102/Ball-Pivoting-Algorithm#8]
1. Visualizer class wont compile 
 pcd.colors = o3d.Vector3dVector(black_colors)

need to change all access to  Vector3dVector with utility 
o3d.utility.Vector3dVector(black_colors)

2. after run it crash for me
0%|          | 0/10 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "C:/Users/User.000/PycharmProjects/deep/GitHub/Ball-Pivoting-Algorithm/testMic.py", line 8, in <module>
    **bpa.create_mesh(limit_iterations=10)#1000**
  File "C:\Users\User.000\PycharmProjects\deep\GitHub\Ball-Pivoting-Algorithm\bpa.py", line 153, in create_mesh
    **self.visualizer.update(edges=self.grid.edges, grid_triangles=self.grid.triangles, color='red')**
  File "C:\Users\User.000\PycharmProjects\deep\GitHub\Ball-Pivoting-Algorithm\visualizer.py", line 99, in update
    **self.visualizer.update_geometry()**
TypeError: update_geometry(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.visualization.Visualizer, geometry: open3d.cpu.pybind.geometry.Geometry) -> bool

Invoked with: Visualizer with name Open3D

**Comment by Lotemn102** [comment]
As i asked in the e-mail, please provide the following details regarding the machine you are using:
- os
- python version
- open3d version 

I can't re-produce your bug without these

**Comment by michaelscheinfeild** [comment]
- Windows 10 Home

64-bit operating system, x64-based processor
Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz   3.10 GHz

- Python 3.7

- Open3d 0.15.1

Thanks Michael

**Comment by Lotemn102** [comment]
Thanks

I'm having the same error, it has something to do with the `open3d` version. It will take me some time to upgrade the project to the newest version. In the meantime, try using version `0.7.0.0` of open3d.

Builds can be found in the official open3d repository:
> https://github.com/isl-org/Open3D/releases/tag/v0.7.0

Let me know if you manage to run it with this way

**Comment by michaelscheinfeild** [comment]
after take open3d-python 0.7.0.0 it draw only 2 triangles and exits
 bpa = BPA(path='data/bunny_with_normals.txt', radius=0.005, visualizer=True)
 bpa.create_mesh(limit_iterations=10000)

![image](https://user-images.githubusercontent.com/21763909/160244523-d851f841-0451-46a9-8624-cd9042013730.png)

**Comment by michaelscheinfeild** [comment]
class Grid
init 
    def init_with_data(self, list_of_points):
        min_x, max_x, min_y, max_y, min_z, max_z = 0, 0, 0, 0, 0, 0

  min should initialized as max of float as example

**Comment by Lotemn102** [comment]
Try to decrease the ball's radius, for example:
```python
 bpa = BPA(path='../data/bunny_with_normals.txt', radius=0.0005, visualizer=True)
  bpa.create_mesh(limit_iterations=900)
  bpa.visualizer.lock()
```

Let me know if you can get better result. 

As for your second comment, i'm not sure i understand: Is it related to this issue? Why is that a problem at all?

**Comment by Lotemn102** [comment]
I'm closing this issue due to lack of activity. If it's still a problem, PM me.

**Comment by ndru2** [comment]
About this problem
TypeError: update_geometry(): incompatible function arguments. The following argument types are supported:
(self: open3d.cpu.pybind.visualization.Visualizer, geometry: open3d.cpu.pybind.geometry.Geometry) -> bool
Invoked with: Visualizer with name Open3D

Add some changes:
line 99 
self.visualizer.update_geometry(line_set)

line 174
vis.update_geometry(line_set)

still one problem - Recursion depth
